#!/usr/bin/env python3
import sys
import argparse
from pathlib import Path
from src.dafny_compiler import DafnyEVMCompiler

def main():
    parser = argparse.ArgumentParser(description='Dafny to EVM Compiler with Formal Verification')
    parser.add_argument('input', help='Input Dafny file')
    parser.add_argument('-o', '--output', help='Output directory', default='build')
    parser.add_argument('--solc', help='Path to solc', default='solc')
    parser.add_argument('--yul-only', action='store_true', help='Generate Yul only')
    parser.add_argument('--skip-verification', action='store_true', help='Skip formal verification')
    parser.add_argument('--no-verify', action='store_true', help='Disable verification (same as --skip-verification)')
    parser.add_argument('--verify-only', action='store_true', help='Only run Dafny verification, no compilation')
    parser.add_argument('--verbose', '-v', action='store_true', help='Show detailed verification output')
    
    args = parser.parse_args()
    
    # Verify-only mode: just run Dafny verification
    if args.verify_only:
        compiler = DafnyEVMCompiler(args.solc, verify=True, verbose=args.verbose)
        result = compiler.compile_file(args.input, skip_verification=False, verify_only=True)
        
        if not result['success']:
            print(f"Verification failed: {result['error']}", file=sys.stderr)
            if 'verification_errors' in result:
                print("\nVerification errors:", file=sys.stderr)
                for error in result['verification_errors']:
                    print(f"  {error}", file=sys.stderr)
            if args.verbose and 'verification_output' in result and result['verification_output']:
                print("\nFull verification output:", file=sys.stderr)
                print(result['verification_output'], file=sys.stderr)
            sys.exit(1)
        
        print("✓ Formal verification PASSED")
        if args.verbose and 'verification_output' in result:
            print("\nVerification details:")
            print(result['verification_output'])
        sys.exit(0)
    
    skip_verify = args.skip_verification or args.no_verify
    compiler = DafnyEVMCompiler(args.solc, verify=not skip_verify, verbose=args.verbose)
    result = compiler.compile_file(args.input, skip_verification=skip_verify)
    
    if not result['success']:
        print(f"Compilation failed: {result['error']}", file=sys.stderr)
        if 'verification_errors' in result:
            print("\nVerification errors:", file=sys.stderr)
            for error in result['verification_errors']:
                print(f"  {error}", file=sys.stderr)
        if args.verbose and 'verification_output' in result and result['verification_output']:
            print("\nFull verification output:", file=sys.stderr)
            print(result['verification_output'], file=sys.stderr)
        sys.exit(1)
    
    output_dir = Path(args.output)
    output_dir.mkdir(exist_ok=True)
    
    contract_name = result['contract_name']
    
    # Show verification status
    if result.get('verified'):
        print(f"✓ Formal verification PASSED")
        if args.verbose and result.get('verification_output'):
            print("\nVerification details:")
            print(result['verification_output'])
    elif not skip_verify:
        print(f"⚠ Verification skipped or unavailable")
    
    yul_file = output_dir / f"{contract_name}.yul"
    with open(yul_file, 'w') as f:
        f.write(result['yul_code'])
    print(f"Generated Yul: {yul_file}")
    
    if not args.yul_only:
        bin_file = output_dir / f"{contract_name}.bin"
        with open(bin_file, 'w') as f:
            f.write(result['bytecode'])
        print(f"Generated bytecode: {bin_file}")
        
        runtime_file = output_dir / f"{contract_name}.bin-runtime"
        with open(runtime_file, 'w') as f:
            f.write(result['runtime_bytecode'])
        print(f"Generated runtime bytecode: {runtime_file}")
        
        print(f"Gas estimate: {result['gas_estimate']} bytes")
    
    print("Compilation successful!")

if __name__ == '__main__':
    main()
